-- 테스트용 데이터베이스 스키마 (H2 문법)

-- 사용자 테이블
CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    picture VARCHAR(500)
);

-- 파티 테이블
CREATE TABLE IF NOT EXISTS party (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    category VARCHAR(20) NOT NULL,
    title VARCHAR(255) NOT NULL,
    limit_people INT NOT NULL,
    limit_price INT DEFAULT 0,
    owner_id BIGINT NOT NULL,
    member_id BIGINT DEFAULT 0,
    is_open BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMP NOT NULL
);

-- 파티 멤버 테이블
CREATE TABLE IF NOT EXISTS partymember (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    party_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(50) DEFAULT 'MEMBER'
);

-- 댓글 테이블
CREATE TABLE IF NOT EXISTS comments (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    party_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 추천 테이블
CREATE TABLE recommendation (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    CATEGORY VARCHAR(255),
    STORE_NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    AVERAGE_RATING FLOAT DEFAULT 0,
    TOTAL_TIME INT,
    PRICE_PER_PERSON INT,
    IS_RESERVATION BOOLEAN,
    RATING_COUNT INT DEFAULT 0,
    DELETED BOOLEAN DEFAULT FALSE,
    DELETED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 추천 댓글 테이블
CREATE TABLE recommendation_comment (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    RECOMMENDATION_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    STAR FLOAT NOT NULL,
    CONTENT VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP,
    DELETED BOOLEAN DEFAULT FALSE
);

-- 추천 시퀀스
CREATE SEQUENCE IF NOT EXISTS RECOMMENDATION_SEQ START WITH 1 INCREMENT BY 1; 